name: Wheel Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel==1.7.4
    - name: install-windows
      if: matrix.os == 'windows-latest'
      run: |
        python -m cibuildwheel --output-dir wheelhouse
      env:
        CIBW_SKIP: "cp27-* pp27-*"  # skip Python 2.7 wheels
        CIBW_BEFORE_ALL: >
          powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/horta/zlib.install/master/install.bat', 'install.bat')"; ./install.bat & "%VS140COMNTOOLS%../../VC/vcvarsall.bat"
        CIBW_ENVIRONMENT: 'INCLUDE="C:/Program Files (x86)/Windows Kits/10/Include/10.0.10240.0/ucrt"'
    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        path: ./wheelhouse/*.whl
